# fly.toml app configuration file generated for discord-bot-portfolio on 2025-06-12T11:46:57+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'discord-bot-portfolio'
primary_region = 'sjc'

[build]

[processes]
app = "npm start"


[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source = "bot_data"
  destination = "/data"

  
